### ISSUE TITLE
Startup freeze

### ISSUE THREAD

**Issue by artivua** [Osiris-Team/AutoPlug-Plugin#7]
Startup freezes on:

[15:06:23 INFO]: [AutoPlug-Plugin] Enabling AutoPlug-Plugin v1.0
[15:06:23 INFO]: [AutoPlug-Plugin] AutoPlug-Client installation was found, connecting...
[15:06:23 INFO]: [AutoPlug-Plugin] Searching AutoPlug-Client on local network...
[15:06:23 INFO]: [AutoPlug-Plugin] Connected to AutoPlug-Client at port 35565 and comparing keys...

BTW I use two servers with autoplug on one machine

**Comment by Osiris-Team** [comment]
For now remove the AutoPlug-Plugin from your server and only use the AutoPlug-Client.
Thanks for reporting, I'll take a look into that.

**Comment by Osiris-Team** [comment]
Are you using a server key btw, or not?

**Comment by vurhe** [comment]
When I tried it with "key: key", startup freezes on "Connected to AutoPlug-Client at port 35565..."

When I tried with real key I recieve:
Connection aborted due to issues! Details: [CON_TYPE: 0] Authentication failed (code:6): An already existing, registered, public server was found with the same ip and port! This server was set to private. Details: ip=46.188.90.87 hostname=46.188.90.87 port=25565
But these servers are private!
![image](https://user-images.githubusercontent.com/65467902/140313039-d6e41c57-2cc7-4ca3-81b5-f89dcac66630.png)

**Comment by artivua** [comment]
I tried both with _key: random text_ and real key
When I use real key, there are no problems with auth:
[15:27][AP][INFO] Authenticating server...
[15:27][AP][INFO] Authentication success!

**Comment by Osiris-Team** [comment]
So you have this freezing when the AutoPlug-Plugin connects to the Client with both ways?

**Comment by artivua** [comment]
Yes

**Comment by artivua** [comment]
Can provide logs if it help

**Comment by Osiris-Team** [comment]
Don't think there should be much to find in the logs.
Maybe look for yourself if you find any related warnings/errors to your problem.

**Comment by Osiris-Team** [comment]
should be fixed in 1.1
